import React, { useEffect, useState } from "react";
import { Button, Dialog, Table, FlexBox, Toolbar, ToolbarSpacer} from '@ui5/webcomponents-react';
import { TableRow, TableCell, TableColumn, Label } from '@ui5/webcomponents-react';
import { getOAData } from "api/OdataManager";

//作業活動情報取得 Odata

export const OASelectDialog = ({ isOpen, closeDialog }) => {
    return (
        <>
            <Dialog 
                id="OASelectDialog"
                open={isOpen}
                style={{ width: "500px"}}
                header={
                    <Toolbar toolbarStyle="Clear">
                    <Label style={{ fontSize: "17px", fontWeight: "bold" }}>
                    作業活動選択
                    </Label>
                  </Toolbar>
                }
                footer={
                    <Toolbar toolbarStyle="Clear">
                      <ToolbarSpacer />
                      <Button 
                        design="Transparent"
                        onClick={closeDialog}
                      >キャンセル
                      </Button>
                    </Toolbar>
                  }
            >
            <Table
                id="OASelectDialogTable"
                style={{ height: "300px", overflow: "auto" }}
                mode="SingleSelect"
                noDataText="データがありません"
                onLoadMore={function _a(){}}
                onPopinChange={function _a(){}}
                onRowClick={function _a(){}}
                onSelectionChange={function _a(){}}                
                stickyColumnHeader
                columns=
                {
                    <>
                    <TableColumn 
                        className="App-TableHeader" 
                        style={{width: '300px'}}
                    >                       
                        <Label>作業</Label>
                    </TableColumn>
                    <TableColumn 
                        className="App-TableHeader" 
                        style={{width: '300px'}}
                    >
                        <Label>作業活動</Label>
                    </TableColumn>
                    <TableColumn 
                        className="App-TableHeader" 
                        style={{width: '300px'}}
                    >
                        <Label>作業区</Label>
                    </TableColumn>
                    <TableColumn 
                        className="App-TableHeader" 
                        style={{width: '300px'}}
                    >
                        <Label>作業区テキスト</Label>
                    </TableColumn>
                    <TableColumn 
                        className="App-TableHeader" 
                        style={{width: '300px'}}
                    >
                        <Label>ステータス</Label>
                    </TableColumn>
                    </>
                }
            >

            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0010
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    処理中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
            <TableRow>
                <TableCell>
                <Label>
                    0100
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    0020
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    Z001
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    デモ作業区
                </Label>
                </TableCell>
                <TableCell>
                <Label>
                    待機中
                </Label>
                </TableCell>
            </TableRow>
           
            </Table>
            <FlexBox
                justifyContent="End"
            >
            </FlexBox>
            </Dialog>
        </>
    )
}